version: '3.7'
services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - "{{ thelounge_home }}:/var/opt/thelounge"
